
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.jflex.test;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ELIMINAR = 55;
  public static final int DIVISION = 66;
  public static final int REAL = 50;
  public static final int PUBLICAS = 6;
  public static final int IDCLASE = 72;
  public static final int INICIOPARENTESIS = 36;
  public static final int VERDADERO = 45;
  public static final int MAYOR = 40;
  public static final int PROPIEDADES = 4;
  public static final int DECREMENTAR = 19;
  public static final int SI = 12;
  public static final int CONSTRUCTOR = 14;
  public static final int LEER = 53;
  public static final int FINALLLAVE = 35;
  public static final int INICIOLLAVE = 34;
  public static final int FALSO = 46;
  public static final int PRIVADOS = 11;
  public static final int DISTINTO = 44;
  public static final int FINALCORCHETE = 33;
  public static final int CADENA_REAL = 57;
  public static final int FINLINEA = 74;
  public static final int HACER = 16;
  public static final int INCREMENTO = 69;
  public static final int COMA = 30;
  public static final int ENTERO = 51;
  public static final int MODULO = 68;
  public static final int IGUAL = 31;
  public static final int CLASE = 2;
  public static final int CADENA_BOLEANO = 58;
  public static final int PRIVADAS = 10;
  public static final int DOSPUNTOS = 27;
  public static final int MENOROIGUAL = 42;
  public static final int PUNTOYCOMA = 29;
  public static final int PROTEGIDOS = 8;
  public static final int INCLUIR = 22;
  public static final int COSENO = 60;
  public static final int DECREMENTO = 70;
  public static final int MAYOROIGUAL = 43;
  public static final int MENOR = 41;
  public static final int NULO = 52;
  public static final int EOF = 0;
  public static final int MIENTRAS = 17;
  public static final int PUNTO = 28;
  public static final int SUMA = 64;
  public static final int FINALPARENTESIS = 37;
  public static final int DEVOLVER = 13;
  public static final int TANGENTE = 61;
  public static final int IGUALQUE = 47;
  public static final int PRINCIPAL = 25;
  public static final int DESTRUCTOR = 15;
  public static final int OR = 39;
  public static final int error = 1;
  public static final int PUBLICOS = 7;
  public static final int RESTA = 65;
  public static final int RAIZ = 63;
  public static final int ID = 71;
  public static final int NUMEROS = 73;
  public static final int ENTONCES = 24;
  public static final int SINO = 23;
  public static final int PROTEGIDAS = 9;
  public static final int EXTIENDE = 3;
  public static final int MULTIPLICACION = 67;
  public static final int ESTATICO = 26;
  public static final int INSTANCIAR = 21;
  public static final int LOGARITMO = 62;
  public static final int INCREMENTAR = 18;
  public static final int CADENA = 48;
  public static final int STRING = 75;
  public static final int BOLEANO = 49;
  public static final int METODOS = 5;
  public static final int SENO = 59;
  public static final int ESCRIBIR = 54;
  public static final int AND = 38;
  public static final int INICIOCORCHETE = 32;
  public static final int CADENA_ENTERO = 56;
  public static final int DESDE = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASE",
  "EXTIENDE",
  "PROPIEDADES",
  "METODOS",
  "PUBLICAS",
  "PUBLICOS",
  "PROTEGIDOS",
  "PROTEGIDAS",
  "PRIVADAS",
  "PRIVADOS",
  "SI",
  "DEVOLVER",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "HACER",
  "MIENTRAS",
  "INCREMENTAR",
  "DECREMENTAR",
  "DESDE",
  "INSTANCIAR",
  "INCLUIR",
  "SINO",
  "ENTONCES",
  "PRINCIPAL",
  "ESTATICO",
  "DOSPUNTOS",
  "PUNTO",
  "PUNTOYCOMA",
  "COMA",
  "IGUAL",
  "INICIOCORCHETE",
  "FINALCORCHETE",
  "INICIOLLAVE",
  "FINALLLAVE",
  "INICIOPARENTESIS",
  "FINALPARENTESIS",
  "AND",
  "OR",
  "MAYOR",
  "MENOR",
  "MENOROIGUAL",
  "MAYOROIGUAL",
  "DISTINTO",
  "VERDADERO",
  "FALSO",
  "IGUALQUE",
  "CADENA",
  "BOLEANO",
  "REAL",
  "ENTERO",
  "NULO",
  "LEER",
  "ESCRIBIR",
  "ELIMINAR",
  "CADENA_ENTERO",
  "CADENA_REAL",
  "CADENA_BOLEANO",
  "SENO",
  "COSENO",
  "TANGENTE",
  "LOGARITMO",
  "RAIZ",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "MODULO",
  "INCREMENTO",
  "DECREMENTO",
  "ID",
  "IDCLASE",
  "NUMEROS",
  "FINLINEA",
  "STRING"
  };
}

