
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.url.compiladores.prueba1;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OPRELACIONAL = 16;
  public static final int NUMERO = 59;
  public static final int DOSPUNTOS = 15;
  public static final int BibliLECT = 57;
  public static final int ELIMINAR = 54;
  public static final int DOBLEIGUAL = 4;
  public static final int EXPONENTE = 30;
  public static final int DEVOLVER = 55;
  public static final int PUNTOYCOMA = 28;
  public static final int TDISPONIBLEP = 50;
  public static final int SI = 38;
  public static final int ENTERO = 36;
  public static final int SIGUAL = 9;
  public static final int TDISPONIBLEM = 49;
  public static final int METODO = 47;
  public static final int RESTA = 11;
  public static final int CORCHETEC = 24;
  public static final int ENTONCES = 39;
  public static final int CORCHETEA = 23;
  public static final int BOOLTEXT = 25;
  public static final int MAYMEN = 7;
  public static final int INSTANCIAR = 53;
  public static final int PARENTESISC = 20;
  public static final int PARENTESISA = 19;
  public static final int PRINCIPAL = 44;
  public static final int IDENTIFICADOR = 61;
  public static final int SINO = 40;
  public static final int IGUALMAYMEN = 6;
  public static final int ESCRIBIR = 43;
  public static final int DESTRUCTOR = 46;
  public static final int CADTEXTO = 62;
  public static final int SUMA = 10;
  public static final int NAMECLASS = 52;
  public static final int DECIMAL = 60;
  public static final int EOF = 0;
  public static final int PROPIEDAD = 48;
  public static final int CLASE = 51;
  public static final int COMILLAS = 3;
  public static final int error = 1;
  public static final int NULO = 35;
  public static final int COMA = 29;
  public static final int BibliPRINT = 58;
  public static final int THEPARENTHESIS = 32;
  public static final int OPBOLEANO = 27;
  public static final int CADENA = 34;
  public static final int MOD = 14;
  public static final int OPATRIBUCION = 17;
  public static final int BOLEANO = 37;
  public static final int REAL = 33;
  public static final int NEGAR = 5;
  public static final int PUNTO = 8;
  public static final int INCLUIR = 56;
  public static final int CONSTRUCTOR = 45;
  public static final int LEER = 42;
  public static final int OPARBOOL = 31;
  public static final int FINLINEA = 2;
  public static final int OPINCREMENTO = 18;
  public static final int FINSI = 41;
  public static final int DIVISION = 13;
  public static final int LLAVEC = 22;
  public static final int BOOLNUM = 26;
  public static final int LLAVEA = 21;
  public static final int MULTIPLICACION = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FINLINEA",
  "COMILLAS",
  "DOBLEIGUAL",
  "NEGAR",
  "IGUALMAYMEN",
  "MAYMEN",
  "PUNTO",
  "SIGUAL",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MOD",
  "DOSPUNTOS",
  "OPRELACIONAL",
  "OPATRIBUCION",
  "OPINCREMENTO",
  "PARENTESISA",
  "PARENTESISC",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "BOOLTEXT",
  "BOOLNUM",
  "OPBOLEANO",
  "PUNTOYCOMA",
  "COMA",
  "EXPONENTE",
  "OPARBOOL",
  "THEPARENTHESIS",
  "REAL",
  "CADENA",
  "NULO",
  "ENTERO",
  "BOLEANO",
  "SI",
  "ENTONCES",
  "SINO",
  "FINSI",
  "LEER",
  "ESCRIBIR",
  "PRINCIPAL",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "METODO",
  "PROPIEDAD",
  "TDISPONIBLEM",
  "TDISPONIBLEP",
  "CLASE",
  "NAMECLASS",
  "INSTANCIAR",
  "ELIMINAR",
  "DEVOLVER",
  "INCLUIR",
  "BibliLECT",
  "BibliPRINT",
  "NUMERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "CADTEXTO"
  };
}

